export const actionTypes = {
  GET_DATABASE_REQUEST: 'GET_DATABASE_REQUEST',
  GET_DATABASE_SUCCESS: 'GET_DATABASE_SUCCESS',
  GET_DATABASE_FAILURE: 'GET_DATABASE_FAILURE',
  RESET_GET_DATABASE: 'RESET_GET_DATABASE',
}
