export const actionTypes = {
  GET_PAGE_COLLECT_REQUEST: 'GET_PAGE_COLLECT_REQUEST',
  GET_PAGE_COLLECT_SUCCESS: 'GET_PAGE_COLLECT_SUCCESS',
  GET_PAGE_COLLECT_FAILURE: 'GET_PAGE_COLLECT_FAILURE',
  RESET_GET_PAGE_COLLECT: 'RESET_GET_PAGE_COLLECT',
  START_CLOCK: 'START_CLOCK',
}
